# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeySignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KeySignatureNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keySignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.KeySignature')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=2)),
                ('isSharp', models.BooleanField(default=False)),
                ('isFlat', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='keysignaturenote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Note'),
        ),
        migrations.AddField(
            model_name='keysignature',
            name='notes',
            field=models.ManyToManyField(through='MainApp.KeySignatureNote', to='MainApp.Note'),
        ),
    ]
