# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keysignature',
            name='rootNote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='MainApp.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('Ab', 'Ab'), ('A#', 'A#'), ('B', 'B'), ('Bb', 'Bb'), ('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('Db', 'Db'), ('D#', 'D#'), ('E', 'E'), ('Eb', 'Eb'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('Gb', 'Gb'), ('G#', 'G#')], default='A', max_length=2),
        ),
    ]
