# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20160210_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='keysignaturenote',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
